### ISSUE TITLE
Roadmap.md

### ISSUE THREAD

**Issue by AKHarris** [MarvinPerry/my_aed#1]
Push a file called `roadmap.md` to this repo :+1: Once you do make sure to close this issue out.

By the way the url for the automated external defibrilator is http://opendata.dc.gov/datasets/ae96db0a66914f05ab09c83f9e9df15f_9

**Comment by MarvinPerry** [comment]
Ok. Does it just need any file with that name to meet a requirement, or should I push my notes?

Marvin Perry
Open Data Intern
Esri R&D Center, Arlington

**Comment by MarvinPerry** [comment]
added roadmap notes and closed
